version: "3.3"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_CONN_STR
      - INIT_DB
    depends_on:
      - "db" 
  db:
    image: postgres:12-alpine
    ports:
      - "8001:5432"
    environment:
      - POSTGRES_PASSWORD